### ISSUE TITLE
Missing STL for v3.1 Release

### ISSUE THREAD

**Issue by ajlennon** [leapmotion/ProjectNorthStar#42]
Hi guys,

Great project. We're trying to print the mechanicals here at DoES Liverpool. I can't find this from v3.1 BOM. Can somebody point me in the right direction please? [Edit: i.e. can't spot it in the 3D files zip]

#110-005 | 1 | LEFT SLIDE ENDCAP - 3DPRINT

**Comment by BryanChrisBrown** [comment]
Hey @ajlennon I believe we already answered this on the discord, however the end cap piece is intended to just be mirrored in your slicer software. Here's a link to a video on how to do that. https://www.youtube.com/watch?v=ahU7GWtRXQo

**Comment by ajlennon** [comment]
Thanks @BryanChrisBrown !
