### ISSUE TITLE
BOM in proprietary Microsoft Excel format instead of a standard, open one

### ISSUE THREAD

**Issue by Ybalrid** [leapmotion/ProjectNorthStar#5]
The BOM for electronics has been pushed in a non-open format. It would be nicer to have this file as an open document (.ods) file.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/leapmotion/ProjectNorthStar/issues/5#issue-334423699

@Ybalrid, have you tried committing one in a PR? Additionally, which file do you refer to?

**Comment by Ybalrid** [comment]
> > [#5 (comment)](https://github.com/leapmotion/ProjectNorthStar/issues/5#issue-334423699)
> 
> @Ybalrid, have you tried committing one in a PR? Additionally, which file do you refer to?


this was 6 years ago, I have no clue what is going on around here now.

A bunch of people made a bunch of open source kits to build one of those headsets, I have lost interest in this since then. I'm closing this.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/leapmotion/ProjectNorthStar/issues/5#event-14906360347

@Ybalrid, probably better to close this as invalid/unplanned then.
